fix: corrected domain value lookup for labels
geocortex/workflow-activities-utility-network pull request #17
Opened 2022-04-19 18:25 UTC by cdoak-gh

2022-04-19 22:10 UTC, rcooney requested changes

2022-04-19 22:10 UTC, rcooney commented on src/activities/utils.ts
> +                    domain = domains[field];
I don't think this is correct. You need the value of the layer's `typeIdField` to determine which domain applies to the current type.

The same thing goes for subtypes. They are about the same, but you need the value of the layer's `subtypeField` to do the lookup.deter

2022-04-21 19:19 UTC, cdoak-gh commented on src/activities/utils.ts
> +                        break;
fixed

2022-04-21 22:58 UTC, cdoak-gh commented on src/activities/utils.ts
> +                            if(value) {
I refactored the lookup which removes this check.

2022-04-21 22:59 UTC, cdoak-gh commented on src/activities/utils.ts
> +                    domain = domains[field];
Refactored lookup to use the subtype field.

2022-04-22 00:56 UTC, rcooney requested changes

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +    const layer = graphic.layer as FeatureLayer;
We should pass the `FeatureLayer` in to the function as a parameter. This cast only works because the caller previously just assigned a `FeatureLayer`, but since this is an exported function we can't assume that will always be the case.

The same thing happens in `getTerminalIds`. We should fix that too, but I'm fine with doing that later if you like since this PR doesn't touch that code.

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +                const labelVal: string | undefined = getCodedDomainValue(assetTypeDomain, assetTypeCode).toString();
The `.toString()` isn't necessary and it hides a bug. If you remove the `any` return type on `getCodedDomainValue` you'll see that it actually returns `string | undefined`.

You could probably change line 79 to be `if (labelVal) {` since an empty string isn't going to be useful.

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +                const labelVal: string | undefined = getCodedDomainValue(assetTypeDomain, assetTypeCode).toString();
While we are at it `getCodedDomainValue` should be renamed `getCodedValueDomainName`.

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +                const labelVal: string | undefined = getCodedDomainValue(assetTypeDomain, assetTypeCode).toString();
Actually we don't need `getCodedDomainValue` at all. `CodedValueDomain` has a `getName(string | number)` method on it that the caller should use instead.

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +        const subtypeField = layer.sourceJSON.subtypeField;
We should flip the order of these. Domains coming from subtypes should be preferred over the ones on the fields.

2022-04-22 00:56 UTC, rcooney commented on src/activities/utils.ts
> +    let domain;
The typing isn't right here. `domain` is currently an `any`, we just happen to only assign it a `CodedValueDomain`. 

We also don't need to export the `domainOf` function.

2022-04-22 16:34 UTC, cdoak-gh commented on src/activities/utils.ts
> +    const layer = graphic.layer as FeatureLayer;
I'll leave the getTerminalIds to a separate PR to keep this one to one issue.

2022-04-22 17:23 UTC, cdoak-gh commented on src/activities/utils.ts
> +                const labelVal: string | undefined = getCodedDomainValue(assetTypeDomain, assetTypeCode).toString();
This turns out to be tricky.  A  Subtype's domains are not instantiated CodedValueDomain objects.  I've introduced a check the getCodedDomain function to see whether they are in fact instantiated but right now it's assuming that if they are defined but not CodedValueDomain objects then they must be JSON.
if (domain != undefined && !(domain instanceof CodedValueDomain)){
        return CodedValueDomain.fromJSON(domain);
 }

2022-04-22 17:23 UTC, cdoak-gh commented on src/activities/utils.ts
> +        const subtypeField = layer.sourceJSON.subtypeField;
Done.

2022-04-22 17:24 UTC, cdoak-gh commented on src/activities/utils.ts
> +    let domain;
Fixed

2022-04-29 20:38 UTC, rcooney commented on src/activities/utils.ts
> +    const layer = graphic.layer as FeatureLayer;
This change is still outstanding. We need something like:
`getCodedValueDomain(layer: FeatureLayer,  field: string, graphic: Graphic): CodedValueDomain | undefined`

2022-04-29 22:12 UTC, rcooney approved these changes

2022-04-29 22:13 UTC, merged