fix: Snap network graphic to UN Feature
geocortex/workflow-activities-utility-network pull request #19
Opened 2022-05-27 19:58 UTC by cdoak-gh

Currently the Network Graphic geometry (for starting points and barriers) is captured from the user.  The change snaps the geometry to the selected utility network feature.  For a point, it's a direct swap.  For a polyline, it finds the location along the line.

2022-05-29 14:50 UTC, rcooney requested changes

2022-05-29 14:50 UTC, rcooney commented on src/activities/utils.ts
> +    const line = Polyline.fromJSON(sourceLine.toJSON());
Why can't we call `clone()` here? If the `sourceLine` isn't an actual instance of `Polyline` we should make it the caller's responsibility to fix that.

2022-05-29 14:50 UTC, rcooney commented on src/activities/utils.ts
> +    const buffer = (await geodesicBuffer(flagGeom, 20, "feet")) as Polygon;
Doesn't `nearestCoordinate(geometry, inputPoint)` just do this for you? https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-geometryEngineAsync.html#nearestCoordinate. The documentation for it is pretty light, but it is described better in the other runtimes https://developers.arcgis.com/net/api-reference/api/netwin/Esri.ArcGISRuntime/Esri.ArcGISRuntime.Geometry.GeometryEngine.NearestCoordinate.html

2022-05-30 17:28 UTC, cdoak-gh commented on src/activities/utils.ts
> +    const line = Polyline.fromJSON(sourceLine.toJSON());
fixed

2022-05-30 17:37 UTC, cdoak-gh commented on src/activities/utils.ts
> +    const buffer = (await geodesicBuffer(flagGeom, 20, "feet")) as Polygon;
I think the confusion stems from my effort to reuse code.  You are correct that nearestCoordinate will find the intersection but the code above is actually splitting the line at that point.   To do that we need a cutter that bisects the target line.  I've cleaned up the code  so that getPolylineIntesection calls nearestCoordinate but splitPolyline remains largely the same.

2022-05-31 15:36 UTC, merged