fix: utils cleanup pr
geocortex/workflow-activities-utility-network pull request #26
Opened 2022-07-22 23:44 UTC by cdoak-gh

2022-07-25 18:25 UTC, rcooney requested changes
The `package-lock` changed significantly, but there weren't and changes to the packages. Was this intended to be committed?

2022-07-25 19:21 UTC, cdoak-gh commented
No the package.lock shouldn't have been committed.

2022-07-25 20:46 UTC, rcooney requested changes

2022-07-25 20:46 UTC, rcooney commented on jest.config.js
> +        "node_modules/(?!(@arcgis)/)/core/"
I think you might want something like `"node_modules/(?!(@arcgis/core)/)"` instead.

Why do we need to handle `@arcgis` and `@arcgis/core` differently?

2022-07-25 20:46 UTC, rcooney commented on package.json
> +    ]
Let's get rid of this.

2022-07-25 20:46 UTC, rcooney commented on src/activities/__tests__/InitializeUtilityNetwork.test.ts
> +console.log("****" + JSON.stringify(mockProvider));
We should remove this.

2022-07-25 20:46 UTC, rcooney commented on src/activities/InitializeUtilityNetwork.ts
> +    utils: {
For discussion... What if we moved all these utilities to a separate activity like `GetUtilityNetworkHelper`? They are all static, so there is really no need for them to be associated with the Initialize activity. This would make the Initialize tests simpler. It would make the utils more portable. Right now you can only use them if you also do all the initialization work.

2022-07-25 20:46 UTC, rcooney commented on src/activities/utils.ts
> +export const utils = (function UtilityNetworkUtils(): any {
I think it is the job of the activity to choose the interface of the utilities it exposes.

`utils.ts` should just be a bunch of exported functions. Leave it up to the consumer to decide how to package them up.

2022-07-26 15:57 UTC, cdoak-gh commented on src/activities/utils.ts
> +export const utils = (function UtilityNetworkUtils(): any {
I'll move this to the GetUtilityNetworkHelper activity.

2022-07-26 15:58 UTC, cdoak-gh commented on src/activities/InitializeUtilityNetwork.ts
> +    utils: {
I like it. I'll make the change.

2022-07-26 15:58 UTC, cdoak-gh commented on src/activities/__tests__/InitializeUtilityNetwork.test.ts
> +console.log("****" + JSON.stringify(mockProvider));
done

2022-07-26 15:58 UTC, cdoak-gh commented on package.json
> +    ]
done

2022-07-26 15:58 UTC, cdoak-gh commented on jest.config.js
> +        "node_modules/(?!(@arcgis)/)/core/"
This is a holdover from a frustrating jest issue.  I'll revert it to the original.

2022-08-18 16:28 UTC, rcooney requested changes

2022-08-18 17:03 UTC, cdoak-gh commented on src/activities/GetUtilityNetworkHelper.ts
> + * @displayName GetUtilityNetworkHelper
fixed

2022-08-18 17:03 UTC, cdoak-gh commented on src/activities/GetUtilityNetworkHelper.ts
> +export default class GetUtilityNetworkHelperActivity
fixed

2022-08-18 17:04 UTC, cdoak-gh commented on src/activities/InitializeUtilityNetwork.ts
> +    utilityNetworks: UtilityNetwork[] | undefined;
fixed

2022-08-18 17:04 UTC, cdoak-gh commented on tsconfig.json
> +        "moduleResolution": "node",
fixed

2022-08-18 17:04 UTC, cdoak-gh commented on tsconfig.json
> +    "include": ["src"],
fixed

2022-08-18 17:04 UTC, cdoak-gh commented on src/activities/__mocks__/WebMap.ts
> +        utilityNetworks: mockColl,
removed the unnecessary mock

2022-08-18 22:54 UTC, rcooney approved these changes

2022-08-18 23:22 UTC, merged